name: ☑️ Generate and insert markdown from YAML

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: ["personal-security-checklist.yml"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 🛎️
        uses: actions/checkout@v4

      # Get current date-time (used for commit message)
      - name: Get Date 📅
        id: date
        run: echo "{date}={$(date +'%d-%b-%Y')}" >> $GITHUB_OUTPUT

        # run: echo "::set-output name=date::$(date +'%d-%b-%Y')"
        # run: echo "::set-output name={name}::{value}"

      # Downloads + installs Python (used for running gen scripts)
      - name: Set up Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # Install contents of requirements.txt
      - name: Install dependencies 📥
        run: |
          python -m pip install --upgrade pip
          cd lib && pip install -r requirements.txt

      # The make command triggers all the Python scripts, generates output
      - name: Run make command 🔨
        run: python lib/generate.py

      # Commit and push the outputed JSON files
      - name: Commit and push generated files ⤴️
        run: |
          git config --global user.name "Ian-T-Price"
          git config --global user.email "Ian.T.Price@gmail.com"
          git pull origin master
          git add CHECKLIST.md
          if git diff --staged --quiet; then
            echo "Nothin new added, so nothing to commit, exiting..."
          else
            git commit -m "Updates checklist (auto-generated, on ${{ steps.date.outputs.date }})"
            git push
          fi
